### ISSUE TITLE
doxx folder\file structure

### ISSUE THREAD

**Issue by vrinceanuv** [evertton/grunt-doxx#3]
I encounter the following issue after accessing the documentation:

I have the sidebar with all the files i need, but if i have this type of files:

folder\file.js
folder\file2.js

In the url bar i have **example/docs/folder\file.js.html** instead of **example/docs/folder/file.js.html**
In order to make it display the comments i have to change **"\"** to **"/"** for each file for which i want to see documentation

Is there a fix for this?

Thank you

**Comment by evertton** [comment]
Considering the "\", I suppose that the operating system is Windows. I ran a task in Grunt in Windows 8.1, using the same directory structure and I could replicate the problem. But `grunt-doxx` is just an extension for generating documentation using the [Doxx](https://github.com/FGRibreau/doxx), then such problems should be reported in [Doxx Issues](https://github.com/FGRibreau/doxx/issues).

**Comment by evertton** [comment]
I reported the problem in https://github.com/FGRibreau/doxx/issues/61.
